In [14]:
import numpy as np
import pandas as pd
np.random.seed(123)

##### 1. How likely is it that you roll doubles when rolling two dice?

In [26]:
outcomes = [1,2,3,4,5,6]
sims = 100_000
trials = 2

rolls = pd.DataFrame(np.random.choice(outcomes, (sims, trials)))
rolls.head()

0  1
0  4  4
1  2  5
2  4  3
3  3  1
4  1  4

In [28]:
doubles = rolls[rolls[0] == rolls[1]]
doubles.head()

0  1
0   4  4
5   2  2
13  5  5
20  1  1
21  3  3

In [29]:
len(doubles)/len(rolls)

0.1667

##### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [47]:
#heads is 1, tails is 0
outcomes = [0, 1]
sims = 100_000
trials = 8

flips = pd.DataFrame(np.random.choice(outcomes, (sims, trials)))
flips.head()

0  1  2  3  4  5  6  7
0  0  1  0  0  1  1  0  0
1  0  1  1  1  0  1  0  1
2  0  1  1  1  1  0  0  1
3  0  1  0  0  1  0  1  0
4  0  1  1  0  1  1  1  0

In [48]:
heads = flips.sum(axis=1)
heads.head()

0    3
1    5
2    5
3    3
4    5
dtype: int64

In [49]:
# Prob of getting exactly 3 heads
(heads == 3).mean()

0.22231

In [50]:
# Prob of getting more than 3 heads
(heads > 3).mean()

0.63491

##### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [54]:
webd = .75
ds = .25
bbs = 2
sims = 100_000

data = np.random.random((sims, bbs))
data

array([[0.76901994, 0.84155157],
       [0.41864384, 0.2844702 ],
       [0.84092506, 0.49569105],
       ...,
       [0.34505923, 0.22931901],
       [0.91302138, 0.72185936],
       [0.22371735, 0.17688086]])

In [55]:
ds_bbs = (data < ds).sum(axis=1)
ds_bbs

array([0, 0, 0, ..., 1, 0, 2])

In [57]:
# Prob of seeing ds on both bbs
(ds_bbs == 2).mean()

0.06382

##### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal) You'll need to make a judgement call on how to handle some of your values

In [63]:
u = 3
sd = 1.5
stock = 17
days = 5
sims = 100_000

consumed = np.random.normal(3, 1.5, (sims, days))
consumed

array([[ 2.99530355,  5.40869892,  1.66562915,  4.19379706,  4.53824509],
       [ 0.47614322,  5.04343603,  4.67249937,  2.32490826,  3.00157496],
       [ 3.42629622,  0.95785826,  5.84111496,  2.24609564,  1.44850979],
       ...,
       [ 4.85497506,  3.29046326, -0.38098325,  5.51390499,  3.08343246],
       [ 3.18136205,  0.5773175 ,  2.32387638,  1.98129708,  2.0213897 ],
       [ 4.36548518,  3.9778664 , -0.33330256,  0.97592496,  4.27111458]])

In [64]:
week_consumed = (consumed.sum(axis=1))
week_consumed

array([18.80167377, 15.51856185, 13.91987488, ..., 16.36179252,
       10.08524269, 13.25708854])

In [65]:
# Prob of less than 17 packages bought any given week
(week_consumed < 17).mean()

0.72428

##### 5. Compare Heights
##### 5.a Men have an average height of 178 cm and standard deviation of 8cm.

In [79]:
u_men = 178
sd_men = 8

##### 5.b Women have a mean of 170, sd = 6cm.

In [80]:
u_women = 170
sd_women = 6

##### 5.c Since you have means and standard deviations, you can use np.random.normal to generate observations.

In [81]:
sims = 100_000
men_obs = np.random.normal(u_men, sd_men, sims)
women_obs = np.random.normal(u_women, sd_women, sims)

##### 5.d If a man and woman are chosen at random, what is the likelihood the woman is taller than the man?

In [82]:
(men_obs < women_obs).mean()

0.21185

##### 6.a When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 

In [83]:
sims = 100_000
students = 50
corrupted = 1/250

installs = np.random.random((sims, students))
installs

array([[0.85733427, 0.02997797, 0.68148016, ..., 0.08895904, 0.3690883 ,
        0.87890758],
       [0.26234904, 0.40044343, 0.85496476, ..., 0.86745983, 0.57419071,
        0.76341741],
       [0.66278328, 0.56734781, 0.1284621 , ..., 0.50175719, 0.4965644 ,
        0.02247261],
       ...,
       [0.3840669 , 0.49324819, 0.60296079, ..., 0.73680593, 0.18546396,
        0.01816609],
       [0.87510313, 0.37499914, 0.04688663, ..., 0.42149272, 0.73729418,
        0.29337541],
       [0.67278093, 0.52142844, 0.34058319, ..., 0.36366713, 0.59969282,
        0.20683059]])

In [84]:
fails = (installs < corrupted).sum(axis=1)
fails

array([0, 0, 0, ..., 0, 1, 0])

In [85]:
# Prob of no download fails:
(fails == 0).mean()

0.81831

##### 6.b 100 students?

In [87]:
sims = 100_000
students = 100
corrupted = 1/250

installs = np.random.random((sims, students))
fails = (installs < corrupted).sum(axis=1)
(fails == 0).mean()

0.66858

##### 6.c What is the probability that we observe an installation issue within the first 150 students that download anaconda?

In [91]:
sims = 1
students = 150
corrupted = 1/250

installs = np.random.random((sims, students))
fails = (installs < corrupted).sum(axis=1)
(fails == 0).mean()

1.0

##### 6.d How likely is it that 450 students all download anaconda without an issue?

In [92]:
sims = 100_000
students = 450
corrupted = 1/250

installs = np.random.random((sims, students))
fails = (installs < corrupted).sum(axis=1)
(fails == 0).mean()

0.16362

##### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [98]:
sims = 100_000
truck_show = .7
days = 3

data = np.random.random((sims, days))
truck_no_show = (data > truck).sum(axis=1)
(truck_no_show == 3).mean()

0.02693

##### 7.b How likely is it that a food truck will show up sometime this week?

In [99]:
sims = 100_000
truck_show = .7
days = 7

data = np.random.random((sims, days))
truck_no_show = (data > truck).sum(axis=1)
(truck_no_show < 7).mean()

0.99977

##### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [129]:
sims = 100_000
days = range(365)
people = 23

birthdays = pd.DataFrame(np.random.choice(days, (sims, people)))
birthdays

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0      213    4   91  305  116  266  213  223   83   20  ...  233  112   46   
1      220  159  345    0  310  203   35  363  256  284  ...   76  143  304   
2      311  123  240  353  176    8   90   49  127   12  ...  107  359  282   
3      275  232  122   40  139  176   39  333   88  143  ...   36   88  231   
4      185   75    5  192  348    7  148  191  206  249  ...  311  108  123   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
99995  167  315  192  214    2  131  140  296   39   92  ...   82  243  150   
99996  166   72   19  217   59  289  137   30  166  226  ...  160  281   54   
99997  131   80  307  109  132   27  235  299  101  299  ...  342   98  221   
99998  326  227  139   47  305  150  362  204  263   25  ...  145   49  250   
99999  282  202  203  257  191  204  317  268  260   51  ...   72  176  161   

        16   17   18   19   20   21   22  
0       65  111  323  290  103  177  361  
1      191   29  236  334  197  315  344  
2       23  102  110  217  307  174  106  
3      270   66  301  316  184  336   48  
4      141  277  118  167  295    9  340  
...    ...  ...  ...  ...  ...  ...  ...  
99995  113   64   23  346  265  140   93  
99996   99   31  340   44   81  175  293  
99997  274  246  329  149  334  140  141  
99998   77  353  113  111  185  334  266  
99999  237   53  211  111  190  249  349  

[100000 rows x 23 columns]

In [130]:
def doubles(b):
    if len(b) > len(b.unique()):
        return True
    return False

In [131]:
doubs = birthdays.apply(doubles, axis=1)

In [132]:
(doubs == True).mean()

0.50766

In [134]:
#20 people
sims = 100_000
days = range(365)
people = 20

birthdays = pd.DataFrame(np.random.choice(days, (sims, people)))
doubs = birthdays.apply(doubles, axis=1)
(doubs == True).mean()

0.41138

In [135]:
#40 people
#20 people
sims = 100_000
days = range(365)
people = 40

birthdays = pd.DataFrame(np.random.choice(days, (sims, people)))
doubs = birthdays.apply(doubles, axis=1)
(doubs == True).mean()

0.8904